### ISSUE TITLE
Music is the wrong way around

### ISSUE THREAD

**Issue by morerokk** [Grummus/BetterLoadingScreen#6]
The piano music seems to play when switching worlds, while the general "ticking/beeping" sound effect happens when you log in. The audio files seem to be switched around.

The piano music should play when logging in instead, not when you switch worlds. Not sure why the two music tracks are switched. Is that just on my end?

**Comment by AAMBIENTT** [comment]
Seems like a local issue, try reinstalling your mod

**Comment by morerokk** [comment]
I did reinstall it, but that made no difference.

It seems the piano music simply plays when switching worlds, and the ambient world switch noise plays when logging in. I think these two are simply the wrong way around. Are you saying you hear the piano on the login screen?
